# -*- coding: utf-8 -*-
ASSETS = 'assets'
AUCTIONS = 'auctions'
AWARDS = 'awards'
BIDS = 'bids'
CANCELLATIONS = 'cancellations'
CHANGES = 'changes'
COMPLAINTS = 'complaints'
CONTRACTS = 'contracts'
DOCUMENTS = 'documents'
ELIGIBILITY_DOCUMENTS = 'eligibility_documents'
FINANCIAL_DOCUMENTS = 'financial_documens'
LOTS = 'lots'
PLANS = 'plans'
QUALIFICATION_DOCUMENTS = 'qualificationDocuments'
QUALIFICATIONS = 'qualifications'
QUESTIONS = 'questions'
TENDERS = 'tenders'
